# SPDX-FileCopyrightText: 2024 - 2026 KYSTVERKET
#
# SPDX-License-Identifier: MIT
name: Publish
on:
  push:
    branches: ['main']
permissions:
  packages: write
  contents: write
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.11
        id: gitversion
        with:
          overrideConfig: |
            mode: Mainline
            useConfigFile: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: ko-build/setup-ko@v0.8
      - name: Build and push
        env:
          VERSION: ${{ steps.gitversion.outputs.semVer }}
        run: |
          ko build --tags=$VERSION ./cmd/terraform-registry --bare
      - name: Tag Release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.determine_version.outputs.semVer }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
